In [1]:
from cataclop.ml.pipeline import factories

In [2]:
program = factories.Program.factory('default')

In [3]:
program.predict(dataset_params = {
    'race_id':21795
})

In [4]:
#program.dataset.save()

program.df

,id,age,earnings,final_odds,final_odds_ref,handicap_distance,handicap_weight,herder_id,horse_id,imported_at_player,...,target,pred_knn_10_1,pred_knn_30_1,pred_knn_60_1,pred_knn_90_1,pred_mlp_1,pred_rf_10_1,pred_rf_100_1,pred_rf_30_1,pred_rf_60_1
0,152227,11,40520700,None,10000,2350,0.0,2640,5312,2018-11-24 22:36:26.488339,...,0.0,3.620,3.333333,2.730833,2.791667,-2891.747248,3.845,3.55200,4.491667,3.783333
1,152228,12,127653400,None,10000,2350,0.0,3015,6481,2018-11-24 22:36:26.545513,...,0.0,3.620,3.425000,2.789167,2.859444,-2896.714089,4.030,3.57650,3.730000,3.785000
2,152229,11,18532200,None,10000,2350,0.0,3543,8370,2018-11-24 22:36:26.605464,...,0.0,3.620,3.333333,2.730833,2.791667,-2888.012457,4.605,7.21200,7.448333,7.465000
3,152230,4,10367800,None,10000,2350,0.0,3543,2770,2018-11-24 22:36:26.662780,...,0.0,4.325,3.333333,2.887500,2.803333,-2878.136660,7.660,6.01975,6.320000,6.053750
4,152231,5,9216000,None,10000,2350,0.0,1640,10270,2018-11-24 22:36:26.722161,...,0.0,3.620,3.421667,2.887500,2.751667,-2879.973199,8.975,6.07750,6.850000,6.192500

In [5]:
program.bet(max_odds=None)
bets = program.bets
bets.head()

,id,date,num,odds_ref,odds_final,target,pred,bet,profit,declared_player_count,...,victory_earnings_amax,victory_earnings_amin,victory_earnings_mean,victory_earnings_r,victory_earnings_std,category,sub_category,country,bets,stash
date,,,,,,,,,,,,,,,,,,,,,
2018-11-25,21795,2018-11-25,4,10000,None,pred_knn_10_1,4.325000,1.0,-1.0,5,...,18.664829,16.036452,17.021568,-0.795858,1.089833,ATTELE,AUTOSTART,CHE,1.0,-1.0
2018-11-25,21795,2018-11-25,2,10000,None,pred_knn_30_1,3.425000,1.0,-1.0,5,...,18.664829,16.036452,17.021568,1.507810,1.089833,ATTELE,AUTOSTART,CHE,2.0,-2.0
2018-11-25,21795,2018-11-25,4,10000,None,pred_knn_60_1,2.887500,1.0,-1.0,5,...,18.664829,16.036452,17.021568,-0.795858,1.089833,ATTELE,AUTOSTART,CHE,3.0,-3.0
2018-11-25,21795,2018-11-25,2,10000,None,pred_knn_90_1,2.859444,1.0,-1.0,5,...,18.664829,16.036452,17.021568,1.507810,1.089833,ATTELE,AUTOSTART,CHE,4.0,-4.0
2018-11-25,21795,2018-11-25,4,10000,None,pred_mlp_1,-2878.136660,1.0,-1.0,5,...,18.664829,16.036452,17.021568,-0.795858,1.089833,ATTELE,AUTOSTART,CHE,5.0,-5.0

In [ ]:
a = None
a > 20

In [ ]:
bets['profit'].describe()
bets['date'].min()

In [ ]:
#bb = bets.groupby('id').filter(lambda r: r['num'].nunique() == 1)
bb = bets.groupby('id').filter(lambda r: (r['target'] == 'pred_mlp_1').sum() == 0 and (r['target'] == 'pred_knn_10_1').sum() == 0  )

f = 'sub_category'

for s in bb[f].value_counts().index:
    print("---\n" + s + "\t{:.2f}\n---".format(bb[bb[f] == s]['profit'].sum()))
    for t in bb['target'].value_counts().index:
        bbb = bb[(bb['target'] == t) & (bb['odds_ref'] < 20) & (bb[f] == s)]
        print("{:10s}: \t {:+.2f} \t {:+.0f} \t {:+.2f}".format(t, bbb.profit.sum(), bbb.profit.count(), bbb.profit.mean()) )

In [ ]:
bb[(bb['target'] == 'pred_rf_60_1') & (bb['odds_ref'] < 20) & (bb['category'] == 'ATTELE')][['id', 'odds_ref', 'odds_final', 'target', 'country', 'sub_category', 'profit']]